version: "3.8"

services:
  bob:
    build:
      context: .
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - USERNAME=${USERNAME}
        - SITE_DIRECTORY=${SITE_DIRECTORY}
    ports:
      - "606:80"
    environment:
      BOB: "./bob.sh"
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      SITE_DIRECTORY: ${SITE_DIRECTORY}
    volumes:
      - ${SITE_DIRECTORY}:${SITE_DIRECTORY}
      - ${SSH_DIRECTORY}:${SSH_DIRECTORY}

networks:
  bob_default:
    driver: overlay
    attachable: true